# Define the URL for downloading Diskspd
$url = "https://github.com/microsoft/diskspd/releases/latest/download/DiskSpd.zip"

# Define the installation directory path
$installDir = "d:\temp\\Diskspd"


# Define the log file path
$logFileout = "d:\temp\\Diskspd\logfileout.txt"
$logFileErr = "d:\temp\Diskspd\logfileErr.txt"

# Check if the installation directory exists and delete it if it does
if (Test-Path -Path $installDir -PathType Container) {
    Write-Host "Existing installation directory found. Deleting..."
    Remove-Item -Path $installDir -Force -Recurse
    Write-Host "Deleted existing installation directory."

}

# Create the installation directory
New-Item -ItemType Directory -Path $installDir | Out-Null

# Download Diskspd to the installation directory
Invoke-WebRequest -Uri $url -OutFile "$installDir\diskspd.zip"

# Extract Diskspd to the installation directory
Expand-Archive -Path "$installDir\diskspd.zip" -DestinationPath $installDir

# Verify that Diskspd has been extracted
if (Test-Path -Path "$installDir\x86\diskspd.exe") {
    Write-Host "Diskspd has been downloaded and extracted successfully."
    
# Install Diskspd with logging
    Start-Process -FilePath "$installDir\x86\diskspd.exe" -Wait -RedirectStandardError $logFileErr  -RedirectStandardOutput $logFileout
    Write-Host "Diskspd installation completed. Check the log file for details: $logFileout"

}

else {

    Write-Host "There was an error extracting Diskspd."

}

Start-Sleep -Seconds 10

d:\temp\Diskspd\x86\diskspd.exe -d60 -W15 -C15 -c128M -t2 -o4 -b4k -L -r -Sh -w50 d:\temp\Diskspd\diskspeedtest.dat



#==========================================================================================================================================
#  PowerShell Parameters
#
#  -ArgumentList:  accepted as a single string with the arguments separated by spaces, or as an array of strings separated by commas
#                  Stinrg[]
#  
#  -RedirectStandardError:  sends any errors generated by the process to a file that you specify
#  -RedirectStandardOutput: sends the output generated by the process to a file that you specify
#  -Wait:                   waits for the specified process and its descendants to complete before accepting more input
#
#
#===========================================================================================================================================
